# Dependabot: open PRs when new dependency versions are available
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "react-native-google-mobile-ads"
        versions: [">=16.4.0"]
