import type {LibraryRepository} from './repositories/LibraryRepository';
import type {AuthRepository} from './repositories/AuthRepository';
import type {MovieRepository} from './repositories/MovieRepository';
import type {PreferencesRepository} from './repositories/PreferencesRepository';
import type {PurchaseRepository} from './repositories/PurchaseRepository';
import type {SearchHistoryRepository} from './repositories/SearchHistoryRepository';
import type {ShowRepository} from './repositories/ShowRepository';
import type {TmdbRepository} from './repositories/TmdbRepository';
import type {StreamingRepository} from './repositories/StreamingRepository';
import type {WatchHistoryRepository} from './repositories/WatchHistoryRepository';
import type {WatchlistRepository} from './repositories/WatchlistRepository';
import type {AccountSync} from './services/AccountSync';
import type {AdGateway} from './services/AdGateway';
import type {SupporterNudge} from './services/SupporterNudge';
import type {AnalyticsSink} from './services/AnalyticsSink';
import type {AppConfig} from './services/AppConfig';
import type {AppUpdates} from './services/AppUpdates';
import type {NetworkMonitor} from './services/NetworkMonitor';
import type {NewMoviesNotifier} from './services/NewMoviesNotifier';
import type {StoreServices} from './services/StoreServices';
import type {Diagnostics} from './services/Diagnostics';
import type {DisplayAds} from './services/DisplayAds';
import type {CountryLocation} from './services/CountryLocation';
import type {AvailabilityAlerts} from './services/AvailabilityAlerts';
import type {JournalRepository} from './repositories/JournalRepository';
import type {AnimeRepository} from './repositories/AnimeRepository';
import type {SubscriberAccess} from './services/SubscriberAccess';
import type {PrivacyPreferences} from './services/PrivacyPreferences';

export interface Dependencies {
    privacy: PrivacyPreferences;
    diagnostics: Diagnostics;
    analytics: AnalyticsSink;
    appConfig: AppConfig;
    appUpdates: AppUpdates;
    auth: AuthRepository;
    movies: MovieRepository;
    shows: ShowRepository;
    tmdb: TmdbRepository;
    streaming: StreamingRepository;
    countryLocation: CountryLocation;
    searchHistory: SearchHistoryRepository;
    preferences: PreferencesRepository;
    watchlist: WatchlistRepository;
    library: LibraryRepository;
    watchHistory: WatchHistoryRepository;
    purchases: PurchaseRepository;
    accountSync: AccountSync;
    network: NetworkMonitor;
    newMovies: NewMoviesNotifier;
    storeServices: StoreServices;
    ads: AdGateway;
    displayAds: DisplayAds;
    supporterNudge: SupporterNudge;
    availabilityAlerts?: AvailabilityAlerts;
    journal?: JournalRepository;
    anime?: AnimeRepository;
    subscriberAccess?: SubscriberAccess;
}
