name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: io.github.kunal26das.yify
          releaseFiles: app/debug/app-debug.aab
          inAppUpdatePriority: 5
          userFraction: 0.99
          track: internal